<?php
// BEAS — CSV Export
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../includes/auth.php';
requireLogin();

$db       = getDB();
$date     = $_GET['date']     ?? null;
$from     = $_GET['from']     ?? date('Y-m-01');
$to       = $_GET['to']       ?? date('Y-m-d');
$courseId = (int)($_GET['courseId'] ?? 0);

$where  = [];
$params = [];

if ($date) {
    $where[]  = "a.attendanceDate=?";
    $params[] = $date;
    $filename = "BEAS_Attendance_$date.csv";
} else {
    $where[]  = "a.attendanceDate BETWEEN ? AND ?";
    $params   = [$from, $to];
    $filename = "BEAS_Attendance_{$from}_to_{$to}.csv";
}

if ($courseId) {
    $where[]  = "a.courseId=?";
    $params[] = $courseId;
}

$whereStr = $where ? 'WHERE '.implode(' AND ',$where) : '';

$stmt = $db->prepare("
    SELECT s.surname, s.firstName, s.matricNumber, s.department, s.level,
           c.courseCode, c.courseTitle,
           a.attendanceDate, a.signInTime, a.signOutTime,
           a.totalDuration, a.signInFingerUsed, a.signInStatus,
           a.verificationMethod, a.sessionId, a.academicYear
    FROM attendance a
    JOIN students s ON a.studentId=s.id
    JOIN courses  c ON a.courseId=c.id
    $whereStr
    ORDER BY a.attendanceDate DESC, c.courseCode, a.signInTime ASC
");
$stmt->execute($params);
$rows = $stmt->fetchAll();

header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

$out = fopen('php://output', 'w');

// Header
fputcsv($out, [
    'Surname', 'First Name', 'Matric No.', 'Department', 'Level',
    'Course Code', 'Course Title', 'Date', 'Sign-In Time', 'Sign-Out Time',
    'Duration', 'Finger Used', 'Status', 'Method', 'Session ID', 'Academic Year',
    'Generated By', 'Generated At'
]);

foreach ($rows as $r) {
    fputcsv($out, [
        $r['surname'], $r['firstName'], $r['matricNumber'],
        $r['department'], $r['level'],
        $r['courseCode'], $r['courseTitle'],
        $r['attendanceDate'], $r['signInTime'], $r['signOutTime'] ?? '',
        $r['totalDuration'] ?? '', $r['signInFingerUsed'] ?? '',
        strtoupper($r['signInStatus']),
        strtoupper($r['verificationMethod'] ?? 'FINGERPRINT'),
        $r['sessionId'] ?? '', $r['academicYear'] ?? '',
        currentUser()['full_name'], date('Y-m-d H:i:s')
    ]);
}

fclose($out);
exit;
?>
